
__author__ = 'michal.broucek'

"""
Constants module
- define files extentions
- strings which should search for
"""

PARSING_FOLDER_FILE_NAME_STORAGE="folder_to_parse_name.txt"
JENKINS_PLOT_OUTPUT_FILE="test_coverage_data.csv"

FILE_EXTENTION = ".java"

PACKAGE = "package "

FEATURE = "FEATURE"
SCENARIO = "SCENARIO"
GIVEN = "GIVEN"

TEST_GROUP_LABEL = "@Test"

DESCRIPTION_ITEMS_LIST = ["WHEN", "THEN", "AND"]

ALL_TESTS = "ALL_TESTS"
SMOKE_TESTS = "EHUBO_SMOKE_TEST"
RELEASE_TESTS = "EHUBO_RELEASE_TEST"
REGRESSION_TESTS = "EHUBO_REGRESSION_TEST"
ENVIRONMENTAL_TESTS = "EHUBO_ENVIRONMENTAL_TEST"
EMULATOR_TESTS = "EMULATOR_TEST"
SIMULATOR_TESTS = "EHUBO_SIMULATOR_TEST"
IN_PROGRESS_TESTS = "IN_PROGRESS_TEST"
# New Ehubo feature groups
#NZTA_TESTS = "EHUBO_NZTA_TEST"
OTAP_TESTS = "EHUBO_OTAP_TEST"
GPS_TESTS = "EHUBO_GPS_TEST"
MODEM_TESTS = "EHUBO_MODEM_TEST"
BLUETOOTH_TESTS = "EHUBO_BLUETOOTH_TEST"
IO_TESTS = "EHUBO_IO_TEST"
CAN_TESTS = "EHUBO_CAN_TEST"
DISTANCE_TESTS = "EHUBO_DISTANCE_TEST"
MEMS_TESTS = "EHUBO_MEMS_TEST"
BATTERY_TESTS = "EHUBO_BATTERY_TEST"
LIFECYCLE_TESTS = "EHUBO_LIFECYCLE_TEST"
STORAGE_TESTS = "EHUBO_STORAGE_TEST"
DEGRADED_TESTS = "EHUBO_DEGRADED_TEST"
SECURITY_TESTS = "EHUBO_SECURITY_TEST"
TAMPER_TESTS = "EHUBO_TAMPER_TEST"
TEMPERATURE_TESTS = "EHUBO_TEMPERATURE_TEST"
ASSETTRACKER_TESTS = "EHUBO_ASSETTRACKER_TEST"
INSTALLWIZARD_TESTS = "EHUBO_INSTALLWIZARD_TEST"
STABILITY_TESTS = "EHUBO_STABILITY_TEST"
PERFORMANCE_TESTS = "EHUBO_PERFORMANCE_TEST"
DRIVEBUDDY_TESTS = "EHUBO_DRIVEBUDDY_TEST"
RUC_TESTS = "EHUBO_RUC_TEST"
UI_TESTS = "EHUBO_UI_TEST"
ENDTOEND_TESTS = "EHUBO_ENDTOEND_TEST"
OTHER_TESTS = "EHUBO_OTHER_TEST"


TEST_GROUPS = [SMOKE_TESTS, RELEASE_TESTS, REGRESSION_TESTS, ENVIRONMENTAL_TESTS, IN_PROGRESS_TESTS, EMULATOR_TESTS, SIMULATOR_TESTS,
               OTAP_TESTS, GPS_TESTS, MODEM_TESTS, BLUETOOTH_TESTS, IO_TESTS, CAN_TESTS, DISTANCE_TESTS, MEMS_TESTS, BATTERY_TESTS,
               LIFECYCLE_TESTS, STORAGE_TESTS, DEGRADED_TESTS, SECURITY_TESTS, TAMPER_TESTS, TEMPERATURE_TESTS, ASSETTRACKER_TESTS, INSTALLWIZARD_TESTS,
               STABILITY_TESTS, PERFORMANCE_TESTS, DRIVEBUDDY_TESTS, RUC_TESTS, UI_TESTS, ENDTOEND_TESTS, OTHER_TESTS]

